event_source: http://publisher.site/
kafka:
  brokers:
    - "kafka-broker-1:9092"
    - "kafka-broker-2:9092"
  topic: "tiup-publish-events"
  credentials:
    type: "sasl_plaintext"
    username: "kafka_user"
    password: "kafka_password"

redis:
  addr: "redis-server:6379"
  db: 0
  password: "redis_password"
services:
  tiup:
    # delivery_config_file: "delivery-config.yaml" # should load from config map

  tidbcloud:
    # ops_config_file: "tidbcloud-ops-config.yaml" # should load from config map
