# This rule is not used by the project mac-builder-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to build.tibuild.pingcap.net resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mac-builder-operator
    app.kubernetes.io/managed-by: kustomize
  name: macbuild-viewer-role
rules:
- apiGroups:
  - build.tibuild.pingcap.net
  resources:
  - macbuilds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - build.tibuild.pingcap.net
  resources:
  - macbuilds/status
  verbs:
  - get
