# This rule is not used by the project mac-builder-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the build.tibuild.pingcap.net.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mac-builder-operator
    app.kubernetes.io/managed-by: kustomize
  name: macbuild-editor-role
rules:
- apiGroups:
  - build.tibuild.pingcap.net
  resources:
  - macbuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - build.tibuild.pingcap.net
  resources:
  - macbuilds/status
  verbs:
  - get
