apiVersion: build.tibuild.pingcap.net/v1alpha1
kind: MacBuild
metadata:
  labels:
    app.kubernetes.io/name: mac-builder-operator
    app.kubernetes.io/managed-by: kustomize
  name: macbuild-sample
spec:
  # TODO(user): Add fields here
